### ISSUE TITLE
http-01 challenge: add possibility for resolving against example.com.acme.invalid, simliar to tls-01

### ISSUE THREAD

**Issue by axos88** [ietf-wg-acme/acme#215] opened 2016-11-26 15:48 UTC
Copied from: letsencrypt/acme-spec#242

As you (LE) seem to be strongly concerned over adding the option to adding the possibility to do the challange over alternate ports (some of which I are valid, but all of which can be handled in a secure way nonetheless - such as using a DNS record and other solutions to address have been already stated in here), I propose to add at least an alternate hostname for the http challange.

This would enable us to add a specific virtual host, answering to *.acme.invalid and redirect that to a specific wwhost, which can be used by the certbot to place the necessary files to complete the challange.

It is currently not possible to add global aliases in nginx for example, so this way it would be possible to issue certificates without having to either have certbot modify the nginx config (yes, it's possible to do that in a zero-downtime way, but it makes my sysadmin inner self scream - my software reconfiguring my other software...), or have to add the location redirect to all vhosts, which is not as easy as it sounds when they get generated by different software components.

If we'd say that the challange has to respond for the Host header of example.com.acme.invalid OR example.com (current) that would make all our lives easier, while maintaining a) backward compatibility b) ease of use for the average joe.

Not as easy as with a custom port, but still a lot more easy to automate.

Additional info:

> kelunik commented 4 hours ago
> @axos88 You can redirect /.well-known/acme-challenge/* to another (virtual) host at any time. The validation authority will follow any redirects. You could also use includes to define a common web root just for /.well-known/acme-challenge, that's what I usually do.

> axos88 commented 2 hours ago • edited
> As stated, this is not that easy to do when the server configuration is generated by different software components (chef cookbooks) that one does not have control over. Unfortunately there are no global aliases / redirects in nginx, only per server.
> 
> This would also mean that in order to use letsencrypt, one has to MODIFY the current configuration, 

> rather than ADD a new virtualhost declaration. Modifying something generated by some other actor is always a bad idea (this is one of the reasons conf.d directories exist btw).
> 
> axos88 commented 2 hours ago
> For example: I have an automated installer for an web application, running over let's say ruby on rails. The application is obviously unaware, and should NEVER be aware how it's exposed to the internet. Thus it is unaware of how its SSL certificate is obtained and installed (normally it wouldn't even run on https, but would rely on a forward proxy to terminate the ssl connection, and forward it using http, but that's another matter).
> 
> Now my automated installer installs this software, and also installs and configures nginx for forward proxying. It will configure the nginx vhost, and other things that are needed. I don't know that LE exists, my installer just asks for the path to a certificate and a key.
> 
> Now I sell my software to a third party, who uses my installer (chef cookbook) to install my software on THEIR infrastructure. THEY are smarter then me, and know that LE exists, and want to use it to create the certs.
> 
> Current options:
> 
> They start hacking around the nginx configuration generated by my installer and add the alias - not good, the next update will overwrite their changes, and they won't be able to renew
> They stop nginx every time they need to upgrade the certs for the duration of the verification - unacceptable
> They use dns challenge if they can - usually it cannot be automated, or is a great effort to add dns records automatically.
> They use the tls challenge (although it doesn't supprot nginx yet), and they modify its configuration during every verification, reloading its configuration, etc. Can easily create problems if someone is maintaining the server at the same time, etc.
> OR: They also create a virtualhost accepting connections for *.acme.invalid once during installation, redirect it to a webroot, and have the verification client drop files into that webroot. Configure it once, and it works. Unnecessary to modify configuration files generated by other installers, unnecessary to keep reloading the nginx configuration all the time, less possibility for failure.
> 
> axos88 commented an hour ago
> And let's face it, validation requests to a vhost have NOTHING to do with the software who serves the content on that server. They are intended for a totally different actor (certbot), thus they should be routed to a different vhost, not be mingled into all the other ones as locations and aliases, and such.
> 
> kelunik commented an hour ago
> unnecessary to keep reloading the nginx configuration all the time
> You have to do that anyway for Nginx to use the new certificate instead of the old one.
> 
> Anyway, this is something that should be in the official repository instead and on the ACME mailing list.
> 
> axos88 commented 3 minutes ago
> unnecessary to keep reloading the nginx configuration all the time
> You have to do that anyway for Nginx to use the new certificate instead of the old one.
> True true, but at least you are not modifying configuration.

**Comment by richsalz** [comment] 2016-11-26 17:42
This is about ACME, the IETF protocol that started with the LetsEncrypt base document.  Please make sure to have discussion on the acme@ietf.org mailing list; see https://www.ietf.org/mailman/listinfo/acme about joining that list.  As for your specific suggestion, the Host header isn't part of the payload, so what's to prevent an attacker from grabbing a message and inserting their own Host header?

**Comment by axos88** [comment] 2016-11-26 18:08
I'm not sure what you mean, I would not want to specify the Hostname in the challange request, but for the verification server to try with both hosts example.com and example.com.acme.invalid when trying to download the verification

**Comment by My1** [comment] 2016-12-03 21:45
There's one Problem, you know why TLS-SNI-01 fell right on its face? The Handling of hostnames without a setting. if there's no specific default a server may wither go for random or even go alphabetic, and especially if they go alphabetic it wouldnt be hard to get a host which could take on all the acme challenge if the victim domain is for example on a shared hosting which allows custom certs.

**Comment by axos88** [comment] 2016-12-04 01:25
again, i don't want it to be able to specify what the hostname should be, just have a (fixed) alternate one that is invalid, and thus free to be added to the webserver without modifying the others (example.com.acme.invalid for example.com).

**Comment by My1** [comment] 2016-12-04 01:30
yes but this isnt the point, the problem is if the server gets a request from a name it doesnt recognize how it will react.
and at worst case it just gives the connection to the first host in alphabetical order.
it being invalid or non-user-selectable or fixed doesnt change the problem that a malicious entity could in worst case take all domains that share one IP because the Problem is the DEFAULT, if a connection comes with an unknown name.

**Comment by axos88** [comment] 2016-12-04 09:06
Well such servers are violating the http protocol, i don't think there is much to be done there, nor should be done.

They are serving content for a resource that is not found on the server (host_a/some url) instead of returning a 404. Handling this problem has to be done on the webserver level, and should be reported as a bug,

Not everyone uses php and webroot. In order to use webroot a hack needs to be created in every site to reroute the requests to .well-known/acme-challange to the correct root. Which means that the acme client needs to mutate the configuration of other software on the host. not a good idea. And remove the hack after the verification. Which means it can f up the other software's configuraation. Or it needs to put files under the webroot of other software. Even worse.

Mutating files is usually a very very bad idea. Especially when they are being generated automatically, say with chef, or some other automation tool, and they are regenerated periodically. What prevents the file to be regenerated while the verifiaction is in progress? The chain of ownership of that file is not clear anymore. One configuration file should always be owned by one software only, that can do whatever it wants with it, while others may read it if they want, but I'm even against that when the cmplexity makes it possible to avoid it.

**Comment by axos88** [comment] 2016-12-04 15:27
Also I suggested adding a DNS TXT entry to allow / disallow this behaviour, and it should be disabled by default.

**Comment by bifurcation** [comment] 2016-12-04 16:24
@axos88 Even if these servers are violating the HTTP protocol, this is how they behave.  We have to live in the real world.

I would be comfortable punting this feature to the future.   If we have a need to do something like this, it can be added as a new challenge type.

**Comment by dougbeattie** [comment] 2016-12-22 16:45
According the the CA/B Forum Baseline Requirements the only approved location for the HTTP challenge is in /.well-known/pki-validation starting March 1, 2017.  Any CA issuing certificates under a public root must only use this path or it will be an audit finding.  Is the spec being updated to allow this and to support this deadline which is just 2 months away?

**Comment by cpu** [comment] 2016-12-22 16:55
@dougbeattie The CA/B Forum Baseline Requirements section 3.2.2.4.6 "Agreed Upon Change to  Website" says:

> Confirming the Applicant's control over the requested FQDN by confirming one of the following under the "/.well‐known/pki‐validation" directory, or another path registered with IANA for the purpose of Domain Validation

In my reading the key phrase is "or another path registered with IANA". The `acme` directory has been in the [IANA registry](https://www.iana.org/assignments/well-known-uris/well-known-uris.xml) since 2016-08-18.

I don't believe there is any specification work to be done ahead of this deadline for the HTTP-01 challenge.

**Comment by dougbeattie** [comment] 2016-12-22 17:35
You're right, I forgot that got added towards the end of the ballot process.  Thanks!

**Comment by jsha** [comment] 2017-01-19 20:01
Based on discussion on the ACME list, closing this out as WONTFIX.

**Closed by jsha** 2017-01-19 20:01 UTC
