### ISSUE TITLE
HTTP validation with 301

### ISSUE THREAD

**Issue by dorogarcia** [ietf-wg-acme/acme#430] opened 2018-07-31 12:52 UTC
Hello,

We have an implementation to generate and renew LE certificates when we have 'central server' with SSL Offloading, for example:

Nginx + SSL (443) -> Varnish (listening en port 80) -> webservers (different servers without shared fs).

When webservers detect http traffic, they return 301.

In your doc: https://www.ietf.org/id/draft-ietf-acme-acme-13.txt you say:

"the challenge must be completed over HTTP, not HTTPS."

As i understand, if you request over HTTP and it redirects to same domain over HTTPs, it should be correct. Is there any security reason to don't allow it?

How can i implement HTTP validation with this kind of environments?

Thanks.

./Doro

**Comment by cpu** [comment] 2018-07-31 12:56
Hi @dorogarcia,

This question is better suited to the [Let's Encrypt community forum](https://community.letsencrypt.org). Please ask Let's Encrypt specific questions there.

I'm going to close this issue since it doesn't track an outstanding issue with the draft ACME protocol.

Thanks!

**Closed by cpu** 2018-07-31 12:56 UTC

**Comment by dorogarcia** [comment] 2018-07-31 13:17
Hello,

I am so sorry but i think that i didn't explain properly. I don't have any problem with LE implementation, they by pass your "the challenge must be completed over HTTP, not HTTPS.", the problem is with other services like Sucuri.net (WAF service) that by pass all LE requests to real servers but they are dropping HTTP requests with 301 because you RFC says that they are not allowed to HTTP validation.

So, i understand that if there is not a good reason to limit 301 redirects, it should be allowed in your RFC.

- Letsencrypt validation with with 301 redirect works because they by pass your limit.
- Sucuri.net Stop by pass with 301 based in your RFC.
- ACME says that HTTP validation can not be using 301.
- I ask ACME if it can be modified in your RFC, because i understand like LetsEncrypt that is not good idea limit it, or is there any good reason to limit HTTP+301 validation?

Thanks.

./Doro

**Comment by cpu** [comment] 2018-07-31 13:24
Hi @dorogarcia,

I think there's some confusion at work here. Can you cite specific parts of the draft RFC when you indicate that it does/doesn't allow something? I don't believe what you're suggesting is true.

>  RFC says that they are not allowed to HTTP validation.

The draft RFC says that the **initial** HTTP-01 challenge validation request should be constructed such that the dereferenced domain name is connected to on port 80. The specification says nothing about forbidding subsequent port changes on redirects.

> ACME says that HTTP validation can not be using 301.

That's not correct. [https://tools.ietf.org/html/draft-ietf-acme-acme-13#section-8.3](Section 8.3)  specifically says that servers SHOULD follow redirects:

>  The server SHOULD follow redirects when dereferencing the URL.

This sounds like a problem with Sucuri.net's WAF rules and should be fixed there.

In general ACME does not try to prescribe CA policy and doesn't speak to additional constraints (e.g. Let's Encrypt will follow a redirect but only to port 80/443). This isn't reflected in the specification by-design to allow CAs to make these sorts of choices independent of the validation mechanism's details.

**Comment by cpu** [comment] 2018-07-31 17:34
> Can you confirm in this ticket that HTTP validation with 301 to HTTPs should be followed? please.

Yes, I can confirm Let's Encrypt's validation authority will follow this redirect. I can't speak for any other ACME implementations.

**Comment by dorogarcia** [comment] 2018-07-31 17:46
Hello,

I mean about ACME documentation not LE implementation. My question is, Should all ACME implementations follow redirects?

Thanks.

./Doro

**Comment by cpu** [comment] 2018-07-31 17:55
> My question is, Should all ACME implementations follow redirects?

Yes :-) That's exactly what it says in [Section 8.3](https://tools.ietf.org/html/draft-ietf-acme-acme-13#section-8.3):  "The server SHOULD follow redirects when dereferencing the URL."

The all-caps SHOULD is [IETF terminology](https://tools.ietf.org/html/bcp14) with specific meaning.

**Comment by dorogarcia** [comment] 2018-07-31 17:55
Thanks! ;D
